"""Update models to include CategoryOffer

Revision ID: 01599b082ef7
Revises: 
Create Date: 2024-07-28 17:11:09.275916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01599b082ef7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_name', sa.String(length=100), nullable=False))
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('category_name')

    # ### end Alembic commands ###
