"""Add notes field to Client model

Revision ID: 10a91afb2328
Revises: 01599b082ef7
Create Date: 2024-07-30 13:03:37.900552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10a91afb2328'
down_revision = '01599b082ef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_offer', schema=None) as batch_op:
        batch_op.alter_column('final_price',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('notes')

    with op.batch_alter_table('category_offer', schema=None) as batch_op:
        batch_op.alter_column('final_price',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
